export function FoundationsContent() {
  return (
    <>
      <h4 id="history">Generated by ChatGPT</h4>
      <p>
        <strong>Origins and Conceptualization</strong>
        <br />
        JSON Resume was conceived as a solution to the fragmented and
        inconsistent landscape of resume formats. Traditional resumes, typically
        created in formats like Microsoft Word or PDF, often suffer from
        compatibility issues when parsed by different systems. Recognizing this
        problem, Thomas Davis and Roland Sharp initiated JSON Resume as an
        open-source project to create a universal, machine-readable format for
        resumes.
      </p>
      <p>
        <strong>Development Milestones</strong>
        <br />
        The project began gaining momentum in the early 2010s, with significant
        milestones such as the creation of the JSON Resume schema, the
        development of the first CLI tools, and the establishment of the JSON
        Resume registry. These milestones were driven by community contributions
        and the growing recognition of the need for a standardized resume format
        in the tech industry.
      </p>
      <p>
        <strong>Community Involvement</strong>
        <br />
        Community involvement has been a cornerstone of JSON Resume's
        development. From its inception, the project has relied on contributions
        from developers around the world. These contributions have included
        code, documentation, translations, and the creation of themes. The
        collaborative nature of the project has ensured its continuous
        improvement and adaptation to the evolving needs of job seekers and
        employers.
      </p>
      <br />

      <h4 id="purpose">Purpose</h4>
      <p>
        <strong>Standardization and Interoperability</strong>
        <br />
        The primary purpose of JSON Resume is to standardize the format of
        resumes to ensure they are easily readable and interoperable across
        various platforms. By using JSON, a widely accepted data format, JSON
        Resume makes it possible for resumes to be parsed and displayed
        consistently by different systems.
      </p>
      <p>
        <strong>Flexibility and Customization</strong>
        <br />
        Another key purpose is to provide flexibility and customization. Unlike
        traditional resume formats that can be rigid and difficult to adapt,
        JSON Resume allows users to easily customize their resume's appearance
        using themes. This flexibility is crucial in a diverse job market where
        different industries and roles may require different presentation
        styles.
      </p>
      <p>
        <strong>Simplifying Resume Management</strong>
        <br />
        JSON Resume simplifies the management of resumes. By storing resume data
        in a structured format, it becomes easy to update, modify, and transform
        resumes as needed. This is particularly beneficial for developers and
        technical professionals who may need to frequently update their resumes
        with new skills and experiences.
      </p>
      <br />

      <h4 id="getting-started">Getting Started</h4>
      <p>
        <strong>Creating a JSON Resume</strong>
        <br />
        Getting started with JSON Resume involves creating a resume file in JSON
        format. This file includes various sections such as personal details,
        work experience, education, skills, and projects. Users can manually
        create this file using any text editor or use one of the many available
        tools and editors specifically designed for JSON Resume.
      </p>
      <p>
        <strong>Using the CLI</strong>
        <br />
        The JSON Resume CLI (Command Line Interface) is a powerful tool that
        helps users create, validate, and manage their JSON resumes. It provides
        commands to initialize a new resume, validate the resume against the
        JSON Resume schema, and export the resume to different formats. The CLI
        is available on npm and can be installed using a simple npm command.
      </p>
      <p>
        <strong>Online Editors</strong>
        <br />
        There are several online editors available for JSON Resume, such as
        Jsonresume.io and Resumake.io. These editors provide a user-friendly
        interface for creating and editing JSON resumes without requiring
        knowledge of JSON syntax. They also offer features like live previews
        and theme selection to help users customize their resumes.
      </p>
      <br />

      <h4 id="contributing">Contributing</h4>
      <p>
        <strong>Ways to Contribute</strong>
        <br />
        Contributing to JSON Resume can take many forms. Developers can
        contribute code to the core project, create new themes, or develop tools
        and libraries that integrate with JSON Resume. Non-developers can help
        by improving documentation, translating content into different
        languages, or promoting the project on social media and in professional
        communities.
      </p>
      <p>
        <strong>Submitting Pull Requests</strong>
        <br />
        Contributors can submit pull requests on GitHub to propose changes to
        the project. Each pull request is reviewed by the project maintainers,
        who provide feedback and suggestions. This collaborative review process
        ensures that contributions meet the project's standards and are aligned
        with its goals.
      </p>
      <p>
        <strong>Community Forums and Discussions</strong>
        <br />
        The JSON Resume community is active on various platforms, including
        GitHub Discussions, Reddit, and Stack Overflow. These forums provide a
        space for users to ask questions, share ideas, and collaborate on new
        features and improvements. Engaging with the community is a great way to
        learn more about the project and contribute to its development.
      </p>
      <br />
    </>
  );
}
