/**
 * Regenerates packages/types/dist/index.d.ts from the canonical JSON Resume
 * schema (@jsonresume/schema). Titles are injected into each named sub-schema
 * so json-schema-to-typescript emits stable, hand-chosen interface names; the
 * generated dist is committed so consumers never need to run this build.
 */
import { compile } from 'json-schema-to-typescript';
import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, '..', 'dist');

const resumeSchema = require('@jsonresume/schema/schema.json');
const jobSchema = require('@jsonresume/schema/job-schema.json');

const COMPILE_OPTS = {
  bannerComment: '',
  additionalProperties: true,
  style: { singleQuote: true },
  declareExternallyReferenced: true,
  unknownAny: false,
};

// Deep clone so we never mutate the imported schema modules.
const clone = (o) => JSON.parse(JSON.stringify(o));

/** Assign a `title` to a schema node so the generator names its interface. */
function title(node, name) {
  if (node) node.title = name;
  return node;
}

function buildResumeSchema() {
  const s = clone(resumeSchema);
  s.title = 'Resume';
  const p = s.properties;

  title(p.basics, 'ResumeBasics');
  title(p.basics.properties.location, 'ResumeLocation');
  title(p.basics.properties.profiles.items, 'ResumeProfile');

  title(p.work.items, 'WorkItem');
  title(p.volunteer.items, 'VolunteerItem');
  title(p.education.items, 'EducationItem');
  title(p.awards.items, 'AwardItem');
  title(p.certificates.items, 'CertificateItem');
  title(p.publications.items, 'PublicationItem');
  title(p.skills.items, 'SkillItem');
  title(p.languages.items, 'LanguageItem');
  title(p.interests.items, 'InterestItem');
  title(p.references.items, 'ReferenceItem');
  title(p.projects.items, 'ProjectItem');
  title(p.meta, 'ResumeMeta');

  return s;
}

function buildJobSchema() {
  const s = clone(jobSchema);
  s.title = 'JobDescription';
  // job-schema.json is a draft-07 document; the local location/meta objects
  // do not need named exports for the W1 surface.
  return s;
}

async function main() {
  mkdirSync(distDir, { recursive: true });

  const resumeTs = await compile(buildResumeSchema(), 'Resume', COMPILE_OPTS);
  const jobTsRaw = await compile(
    buildJobSchema(),
    'JobDescription',
    COMPILE_OPTS
  );

  // Both schemas define an identical `iso8601` -> `export type Iso8601 = string;`.
  // It is emitted by the resume compile above, so strip the duplicate from the
  // job output to avoid a "Duplicate identifier" TS error.
  const jobTs = jobTsRaw.replace(
    /\/\*\*[\s\S]*?\*\/\s*export type Iso8601 = string;\s*/,
    ''
  );

  const header = `/**
 * Auto-generated by packages/types/scripts/generate.mjs from
 * @jsonresume/schema (schema.json + job-schema.json). Do not edit by hand;
 * run \`pnpm --filter @jsonresume/types build\` to regenerate.
 */
/* eslint-disable */

`;

  // Strip any leading eslint banner the generator may add, then concatenate.
  const body = [resumeTs.trim(), jobTs.trim()].join('\n\n') + '\n';

  writeFileSync(join(distDir, 'index.d.ts'), header + body, 'utf8');
  // eslint-disable-next-line no-console
  process.stdout.write('Wrote dist/index.d.ts\n');
}

main().catch((err) => {
  process.stderr.write(String(err && err.stack ? err.stack : err) + '\n');
  process.exit(1);
});
